[project]
name = "tjsp_unidades"
version = "0.1.21"
description = "Obtem Unidades Administrativas do Tribunal de Justiça do Estado de São Paulo"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "duckdb>=1.5.5",
    "lxml>=6.1.1",
    "more-itertools>=11.1.0",
    "notebook>=7.5.7",
    "openpyxl>=3.1.5",
    "pandas>=2.0.3",
    "python-dotenv>=1.2.2",
    "requests-cache>=1.3.3",
    "requests-ip-rotator>=1.0.18",
    "xlrd>=2.0.2",
]

[dependency-groups]
docs = [
    "mkdocs>=1.6.1",
    "mkdocs-jupyter>=0.26.3",
    "mkdocs-material[imaging]>=9.7.7",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
# Informa ao Hatchling exatamente onde está o código do pacote
packages = ["tjsp_unidades"]
# Força a inclusão de todos os CSVs dentro da pasta data no wheel final
artifacts = ["**/data/*.csv", "**/data/**/*.csv"]

# Se você quiser que o uv lock garanta que suas dependências continuem funcionando tanto no Python 3.11 quanto em
# versões mais recentes (como 3.12 ou 3.13), use:
# [tool.uv]
# environments = [
#     "python_version >= '3.11'"
# ]

[project.urls]
Issues = "https://github.com/michelmetran/tjsp_unidades/issues/"
Documentation = "https://tjsp-unidades.readthedocs.io/"
Repository = "https://github.com/michelmetran/tjsp_unidades/"
Discussions = "https://github.com/michelmetran/tjsp_unidades/discussions"
